package common;

public enum RequestType {
	LOGIN,
	LOGOUT,
	OPEN_GATE,
	GET_PARKING_STATUS,
	CHANGE_PW,
	RESERVE_PARKING_SPOT,
	ADD_DRIVER,
	REMOVE_DRIVER,
	CANCEL_RESERVATION,
	CHANGE_EXPIRATION,
	GET_NEXT_EXPIRED
}
